@startuml
note "Desde cualquier pagina\nse puede usarse la\nbarra de navegacion" as N1

caption Diagrama de navegacion
title Administrador

hide empty description

State Barra_navegacion

State Gestion_actividad : direccion.xhtml

State Inicio : direccion.xhtml

State Actividades_ofertas : direccion.xhtml
State Informacion_actividad : direccion.xhtml
State Categorias: direccion.xhtml

'State Sesion_iniciada {
    State Panel_control : direccion.xhtml
    State Formulario_datos : direccion.xhtml
'
'    [*] -> Panel_control
'    Panel_control -> Formulario_datos
'}

State fork_Inicio <<fork>>
State Inicio_sesion : direccion.xhtml
State Registro_usuario : direccion.xhtml

State fork_Actividad <<fork>>
State fork_Actividad_Ususario <<fork>>

'State fork_BarraNabegacion <<fork>>
'
'fork_BarraNabegacion -down> Actividades_ofertas
'fork_BarraNabegacion -down> Inici

[*] --> Inicio
Inicio -> fork_Inicio : Usuario\nno inicializado
Inicio -> Panel_control :  Usuario\ninicializado
Inicio -right-> fork_Actividad

Barra_navegacion -> fork_Inicio : Usuario\nno inicializado
Barra_navegacion --> Actividades_ofertas
Barra_navegacion -> Panel_control : Usuario\ninicializado

fork_Inicio -> Registro_usuario
fork_Inicio --> Inicio_sesion


'Inicio_sesion -> Sesion_iniciada
Inicio_sesion --> Panel_control
Inicio_sesion -right> Registro_usuario

Registro_usuario --> Formulario_datos
Registro_usuario -left> Inicio_sesion

Panel_control -> Formulario_datos
Panel_control --> fork_Actividad_Ususario : Actividade\na gestionar

fork_Actividad_Ususario --> Actividades_ofertas
fork_Actividad_Ususario --> Informacion_actividad

fork_Actividad --> Categorias
fork_Actividad --> Actividades_ofertas
fork_Actividad --> Informacion_actividad

Informacion_actividad --> Gestion_actividad : Uniario\nadministrador\niniciado

Categorias -> Actividades_ofertas

Actividades_ofertas -> Informacion_actividad


@enduml