-- MySQL Script generated by MySQL Workbench
-- Tue Mar 31 00:10:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sii
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sii` ;

-- -----------------------------------------------------
-- Schema sii
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sii` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sii` ;

-- -----------------------------------------------------
-- Table `sii`.`CONVALIDACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`CONVALIDACION` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `CREDITOSMAXIMO` DOUBLE NULL DEFAULT NULL,
  `DESCRIPCION` VARCHAR(255) NULL DEFAULT NULL,
  `EVALUACION` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sii`.`ESTADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`ESTADO` (
  `ID` BIGINT NOT NULL,
  `ESTADOTYPE` VARCHAR(255) NULL DEFAULT NULL,
  `MENSAJE` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sii`.`ACTIVIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`ACTIVIDAD` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `CALIFICACION` INT NULL DEFAULT NULL,
  `DESCRIPCION` VARCHAR(255) NULL DEFAULT NULL,
  `FECHAAPERTURAPLAZAS` DATE NULL DEFAULT NULL,
  `FECHACIERREPLAZAS` DATE NULL DEFAULT NULL,
  `FECHAPUBLICADA` DATE NULL DEFAULT NULL,
  `HORASINVERTIDA` DOUBLE NULL DEFAULT NULL,
  `IMAGEN` VARCHAR(255) NULL DEFAULT NULL,
  `NUMEROPLAZAS` INT NULL DEFAULT NULL,
  `TITULO` VARCHAR(255) NULL DEFAULT NULL,
  `CONVALIDACION_ID` BIGINT NULL DEFAULT NULL,
  `ESTADO_ID` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_ACTIVIDAD_CONVALIDACION_ID` (`CONVALIDACION_ID` ASC) VISIBLE,
  INDEX `FK_ACTIVIDAD_ESTADO_ID` (`ESTADO_ID` ASC) VISIBLE,
  CONSTRAINT `FK_ACTIVIDAD_CONVALIDACION_ID`
    FOREIGN KEY (`CONVALIDACION_ID`)
    REFERENCES `sii`.`CONVALIDACION` (`ID`),
  CONSTRAINT `FK_ACTIVIDAD_ESTADO_ID`
    FOREIGN KEY (`ESTADO_ID`)
    REFERENCES `sii`.`ESTADO` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sii`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`USUARIO` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `DTYPE` VARCHAR(31) NULL DEFAULT NULL,
  `APELLIDOS` VARCHAR(255) NULL DEFAULT NULL,
  `CONTRASENA` VARCHAR(255) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(255) NULL DEFAULT NULL,
  `NOMBRE` VARCHAR(255) NULL DEFAULT NULL,
  `TELEFONO` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sii`.`COMENTARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`COMENTARIO` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `CONTENIDO` VARCHAR(255) NULL DEFAULT NULL,
  `DEMANDANTE_ID` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_COMENTARIO_DEMANDANTE_ID` (`DEMANDANTE_ID` ASC) VISIBLE,
  CONSTRAINT `FK_COMENTARIO_DEMANDANTE_ID`
    FOREIGN KEY (`DEMANDANTE_ID`)
    REFERENCES `sii`.`USUARIO` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sii`.`ACTIVIDAD_COMENTARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`ACTIVIDAD_COMENTARIO` (
  `Actividad_ID` BIGINT NOT NULL,
  `comentarios_ID` BIGINT NOT NULL,
  PRIMARY KEY (`Actividad_ID`, `comentarios_ID`),
  INDEX `FK_ACTIVIDAD_COMENTARIO_comentarios_ID` (`comentarios_ID` ASC) VISIBLE,
  CONSTRAINT `FK_ACTIVIDAD_COMENTARIO_Actividad_ID`
    FOREIGN KEY (`Actividad_ID`)
    REFERENCES `sii`.`ACTIVIDAD` (`ID`),
  CONSTRAINT `FK_ACTIVIDAD_COMENTARIO_comentarios_ID`
    FOREIGN KEY (`comentarios_ID`)
    REFERENCES `sii`.`COMENTARIO` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sii`.`ETIQUETA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`ETIQUETA` (
  `NOMBRE` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`NOMBRE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sii`.`ACTIVIDAD_ETIQUETA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`ACTIVIDAD_ETIQUETA` (
  `Actividad_ID` BIGINT NOT NULL,
  `clasificacion_NOMBRE` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Actividad_ID`, `clasificacion_NOMBRE`),
  INDEX `FK_ACTIVIDAD_ETIQUETA_clasificacion_NOMBRE` (`clasificacion_NOMBRE` ASC) VISIBLE,
  CONSTRAINT `FK_ACTIVIDAD_ETIQUETA_Actividad_ID`
    FOREIGN KEY (`Actividad_ID`)
    REFERENCES `sii`.`ACTIVIDAD` (`ID`),
  CONSTRAINT `FK_ACTIVIDAD_ETIQUETA_clasificacion_NOMBRE`
    FOREIGN KEY (`clasificacion_NOMBRE`)
    REFERENCES `sii`.`ETIQUETA` (`NOMBRE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sii`.`EVENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`EVENTO` (
  `ID` BIGINT NOT NULL,
  `DESCRIPCION` VARCHAR(255) NULL DEFAULT NULL,
  `FECHA` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sii`.`ACTIVIDAD_EVENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`ACTIVIDAD_EVENTO` (
  `Actividad_ID` BIGINT NOT NULL,
  `eventos_ID` BIGINT NOT NULL,
  PRIMARY KEY (`Actividad_ID`, `eventos_ID`),
  INDEX `FK_ACTIVIDAD_EVENTO_eventos_ID` (`eventos_ID` ASC) VISIBLE,
  CONSTRAINT `FK_ACTIVIDAD_EVENTO_Actividad_ID`
    FOREIGN KEY (`Actividad_ID`)
    REFERENCES `sii`.`ACTIVIDAD` (`ID`),
  CONSTRAINT `FK_ACTIVIDAD_EVENTO_eventos_ID`
    FOREIGN KEY (`eventos_ID`)
    REFERENCES `sii`.`EVENTO` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sii`.`SOLICITUD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`SOLICITUD` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NOTA` INT NULL DEFAULT NULL,
  `ESTADO_ID` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_SOLICITUD_ESTADO_ID` (`ESTADO_ID` ASC) VISIBLE,
  CONSTRAINT `FK_SOLICITUD_ESTADO_ID`
    FOREIGN KEY (`ESTADO_ID`)
    REFERENCES `sii`.`ESTADO` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sii`.`ACTIVIDAD_SOLICITUD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`ACTIVIDAD_SOLICITUD` (
  `Actividad_ID` BIGINT NOT NULL,
  `solicitudes_ID` BIGINT NOT NULL,
  PRIMARY KEY (`Actividad_ID`, `solicitudes_ID`),
  INDEX `FK_ACTIVIDAD_SOLICITUD_solicitudes_ID` (`solicitudes_ID` ASC) VISIBLE,
  CONSTRAINT `FK_ACTIVIDAD_SOLICITUD_Actividad_ID`
    FOREIGN KEY (`Actividad_ID`)
    REFERENCES `sii`.`ACTIVIDAD` (`ID`),
  CONSTRAINT `FK_ACTIVIDAD_SOLICITUD_solicitudes_ID`
    FOREIGN KEY (`solicitudes_ID`)
    REFERENCES `sii`.`SOLICITUD` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sii`.`ADMINISTRADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`ADMINISTRADOR` (
  `ID` BIGINT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_ADMINISTRADOR_ID`
    FOREIGN KEY (`ID`)
    REFERENCES `sii`.`USUARIO` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sii`.`DEMANDANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`DEMANDANTE` (
  `ID` BIGINT NOT NULL,
  `DATOSDEINTERES` VARCHAR(255) NULL DEFAULT NULL,
  `EDAD` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_DEMANDANTE_ID`
    FOREIGN KEY (`ID`)
    REFERENCES `sii`.`USUARIO` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sii`.`DEMANDANTE_ETIQUETA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`DEMANDANTE_ETIQUETA` (
  `Demandante_ID` BIGINT NOT NULL,
  `intereses_NOMBRE` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Demandante_ID`, `intereses_NOMBRE`),
  INDEX `FK_DEMANDANTE_ETIQUETA_intereses_NOMBRE` (`intereses_NOMBRE` ASC) VISIBLE,
  CONSTRAINT `FK_DEMANDANTE_ETIQUETA_Demandante_ID`
    FOREIGN KEY (`Demandante_ID`)
    REFERENCES `sii`.`USUARIO` (`ID`),
  CONSTRAINT `FK_DEMANDANTE_ETIQUETA_intereses_NOMBRE`
    FOREIGN KEY (`intereses_NOMBRE`)
    REFERENCES `sii`.`ETIQUETA` (`NOMBRE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sii`.`DEMANDANTE_SOLICITUD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`DEMANDANTE_SOLICITUD` (
  `Demandante_ID` BIGINT NOT NULL,
  `solicitudes_ID` BIGINT NOT NULL,
  PRIMARY KEY (`Demandante_ID`, `solicitudes_ID`),
  INDEX `FK_DEMANDANTE_SOLICITUD_solicitudes_ID` (`solicitudes_ID` ASC) VISIBLE,
  CONSTRAINT `FK_DEMANDANTE_SOLICITUD_Demandante_ID`
    FOREIGN KEY (`Demandante_ID`)
    REFERENCES `sii`.`USUARIO` (`ID`),
  CONSTRAINT `FK_DEMANDANTE_SOLICITUD_solicitudes_ID`
    FOREIGN KEY (`solicitudes_ID`)
    REFERENCES `sii`.`SOLICITUD` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sii`.`OFERTANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`OFERTANTE` (
  `ID` BIGINT NOT NULL,
  `CALIFICACION` DOUBLE NULL DEFAULT NULL,
  `DIRECCION` VARCHAR(255) NULL DEFAULT NULL,
  `NIF` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_OFERTANTE_ID`
    FOREIGN KEY (`ID`)
    REFERENCES `sii`.`USUARIO` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sii`.`Ofertante_CONTACTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`Ofertante_CONTACTO` (
  `Ofertante_ID` BIGINT NULL DEFAULT NULL,
  `CONTACTO` VARCHAR(255) NULL DEFAULT NULL,
  INDEX `FK_Ofertante_CONTACTO_Ofertante_ID` (`Ofertante_ID` ASC) VISIBLE,
  CONSTRAINT `FK_Ofertante_CONTACTO_Ofertante_ID`
    FOREIGN KEY (`Ofertante_ID`)
    REFERENCES `sii`.`USUARIO` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sii`.`SEQUENCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`SEQUENCE` (
  `SEQ_NAME` VARCHAR(50) NOT NULL,
  `SEQ_COUNT` DECIMAL(38,0) NULL DEFAULT NULL,
  PRIMARY KEY (`SEQ_NAME`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sii`.`USUARIO_ACTIVIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sii`.`USUARIO_ACTIVIDAD` (
  `Usuario_ID` BIGINT NOT NULL,
  `actividades_ID` BIGINT NOT NULL,
  PRIMARY KEY (`Usuario_ID`, `actividades_ID`),
  INDEX `FK_USUARIO_ACTIVIDAD_actividades_ID` (`actividades_ID` ASC) VISIBLE,
  CONSTRAINT `FK_USUARIO_ACTIVIDAD_actividades_ID`
    FOREIGN KEY (`actividades_ID`)
    REFERENCES `sii`.`ACTIVIDAD` (`ID`),
  CONSTRAINT `FK_USUARIO_ACTIVIDAD_Usuario_ID`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `sii`.`USUARIO` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
